services:
  docs:
    image: todo_1_local_docs
    container_name: todo_1_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./todo_1:/app/todo_1:z
    ports:
      - '9000:9000'
    command: /start-docs
